### PR TITLE
Update BOT info

### PR DESCRIPTION
**Pull request by abrandemuehl**

### CODE REVIEW

**Comment by abrandemuehl** [comment]
Should I just merge this? Do the changes get propagated automatically?

**Comment by sameetandpotatoes** [comment]
Yeah, go ahead and merge, and we can update the store in production with these changes.

**Comment by abrandemuehl** [comment]
@sameetandpotatoes Can you update the production store? It still hasn't been changed

**Comment by sameetandpotatoes** [comment]
@abrandemuehl It's been updated. Sorry about the delay.

**Pull request merged**
