### PR TITLE
Add chair contact field to committees, sigs

### PR DESCRIPTION
**Pull request by benpankow**
To be potentially used for display - most are unfilled, netids used where known

### CODE REVIEW

**Comment by bcongdon** [comment]
What does `chairContact` denote exactly? Netids? Slack ids?

**Comment by benpankow** [comment]
Slack ids eventually, @narendasan told me to fill it with netids for now.

**Comment by narendasan** [comment]
@tommypacker @rauhul, can you guys collect the slack ids of the SIG Chairs?

**Comment by ASankaran** [comment]
Please, reopen if we go about implementing this in the future.

**Pull request closed without merging**
